[project]
name = "pyptv2-env"
version = "0.1.0"
description = "Environment for pyptv2 development"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
pip = "*"
setuptools = "*"
wheel = "*"
numpy = "<=1.26.0"  # Use compatible NumPy version
cython = "<3.0.0"   # Use Cython 0.29.x which is more compatible
pytest = "*"
